<?php

add_action('init', function () {
    if (!function_exists('pll_register_string')) {
        return;
    }
    pll_register_string('Order number', 'Order number:', 'WooCommerce');
    pll_register_string('Order date', 'Date:', 'WooCommerce');
    pll_register_string('Order email', 'Email:', 'WooCommerce');
    pll_register_string('Order total', 'Total:', 'WooCommerce');
    pll_register_string('Payment method', 'Payment method:', 'WooCommerce');
    pll_register_string('Order details', 'Order details', 'WooCommerce');
    pll_register_string('Product', 'Product', 'WooCommerce');
    pll_register_string('Total', 'Total', 'WooCommerce');
    pll_register_string('Meni za ovu nedelju', 'Meni za ovu nedelju');
    pll_register_string('Meni se objavljuje svake nedelje u sedmici.', 'Meni se objavljuje svake nedelje u sedmici.');
    pll_register_string('Ponedeljak', 'Ponedeljak');
    pll_register_string('Utorak', 'Utorak');
    pll_register_string('Sreda', 'Sreda');
    pll_register_string('Cetvrtak', 'Cetvrtak');
    pll_register_string('Petak', 'Petak');
    pll_register_string('Subota', 'Subota');
    pll_register_string('Doručak', 'Doručak');
    pll_register_string('Užina 1', 'Užina 1');
    pll_register_string('Ručak', 'Ručak');
    pll_register_string('Užina 2', 'Užina 2');
    pll_register_string('Večera', 'Večera');
    pll_register_string('Naruči svoj paket', 'Naruči svoj paket');
    pll_register_string('Pol', 'Pol');
    pll_register_string('Muško', 'Muško');
    pll_register_string('Žensko', 'Žensko');
    pll_register_string('Kalorije', 'Kalorije');
    pll_register_string('Tip paketa', 'Tip paketa');
    pll_register_string('Datum dostave', 'Datum dostave');
    pll_register_string('Proizvod je uspešno dodat u korpu', 'Proizvod je uspešno dodat u korpu');
    pll_register_string('Izaberi paket', 'Izaberi paket');
    pll_register_string('Na osnovu odabira paketa, cene planova se menjaju', 'Na osnovu odabira paketa, cene planova se menjaju');
    pll_register_string('Izaberi plan', 'Izaberi plan');
    pll_register_string('Dnevni', 'Dnevni');
    pll_register_string('RSD po danu', 'RSD po danu');
    pll_register_string('RSD', 'RSD');
    pll_register_string('Nedeljni 5', 'Nedeljni 5');
    pll_register_string('(radni dani)', '(radni dani)');
    pll_register_string('Nedeljni 6', 'Nedeljni 6');
    pll_register_string('(radni dani i subota)', '(radni dani i subota)');
    pll_register_string('Mesečni 20', 'Mesečni 20');
    pll_register_string('Mesečni 24', 'Mesečni 24');
    pll_register_string('Izaberi datum za naručivanje', 'Izaberi datum za naručivanje');
    pll_register_string('Cena paketa:', 'Cena paketa:');
    pll_register_string('Dodaj u korpu', 'Dodaj u korpu');
    pll_register_string('Naruči odmah', 'Naruči odmah');
    pll_register_string('kcal', 'kcal');
    pll_register_string('Plan ishrane', 'Plan ishrane');
    pll_register_string('Najnovije', 'Najnovije');
    pll_register_string('Nazad na prodavnicu', 'Nazad na prodavnicu');
    pll_register_string('Nazad na početnu', 'Nazad na početnu');
    pll_register_string('Vaša korpa je prazna', 'Vaša korpa je prazna');
    pll_register_string('Naruči Kombo paket', 'Naruči Kombo paket');
    pll_register_string('Oops! Stranica nije pronađena', 'Oops! Stranica nije pronađena');
    pll_register_string('Čini se da stranica koju tražite ne postoji. Možda ste pogrešno uneli adresu ili je stranica uklonjena.', 'Čini se da stranica koju tražite ne postoji. Možda ste pogrešno uneli adresu ili je stranica uklonjena.');
    pll_register_string('Greška 404', 'Greška 404');
    pll_register_string('Protein', 'Protein');
    pll_register_string('Slim', 'Slim');
    pll_register_string('Fit', 'Fit');
    pll_register_string('Mali', 'Mali');
    pll_register_string('Veliki', 'Veliki');
    pll_register_string('Izaberi veličinu', 'Izaberi veličinu');
    pll_register_string('Januar', 'Januar');
    pll_register_string('Februar', 'Februar');
    pll_register_string('Mart', 'Mart');
    pll_register_string('April', 'April');
    pll_register_string('Maj', 'Maj');
    pll_register_string('Jun', 'Jun');
    pll_register_string('Jul', 'Jul');
    pll_register_string('Avgust', 'Avgust');
    pll_register_string('Septembar', 'Septembar');
    pll_register_string('Oktobar', 'Oktobar');
    pll_register_string('Novembar', 'Novembar');
    pll_register_string('Decembar', 'Decembar');
    pll_register_string('Cena', 'Cena');
    pll_register_string('nedeljni5', 'nedeljni5');
    pll_register_string('nedeljni6', 'nedeljni6');
    pll_register_string('Datum za naručivanje', 'Datum za naručivanje');
    pll_register_string('Količina', 'Količina');
    pll_register_string('Dostava dostupna samo za Beograd, Novi Sad i Staru i Novu Pazovu', 'Dostava dostupna samo za Beograd, Novi Sad i Staru i Novu Pazovu');
    pll_register_string('Dostava', 'Dostava');
    pll_register_string('Ukupna cena', 'Ukupna cena');
    pll_register_string('Kupi', 'Kupi');
    pll_register_string('Dostava i plaćanje', 'Dostava i plaćanje');
    pll_register_string('Napomena o narudžbini', 'Napomena o narudžbini');
    pll_register_string('Dodajte napomenu za vašu narudžbinu (opciono)', 'Dodajte napomenu za vašu narudžbinu (opciono)');
    pll_register_string('Vaša narudžbina', 'Vaša narudžbina');
    pll_register_string('Dostava kurirskom službom', 'Dostava kurirskom službom');
    pll_register_string('Plaćanje pouzećem', 'Plaćanje pouzećem');
    pll_register_string('od', 'od');
    pll_register_string('do', 'do');
    pll_register_string('View Cart', 'View Cart');
    pll_register_string('Naruči', 'Naruči');
    pll_register_string('Kalendar', 'Kalendar');
    pll_register_string('Plan', 'Plan');
    pll_register_string('Select plan', 'Molimo izaberite plan');
    pll_register_string('Select calories', 'Molimo izaberite kalorije');
    pll_register_string('Select package', 'Molimo izaberite paket');
    pll_register_string('Select date', 'Molimo izaberite datum');
    pll_register_string('Sve cene su sa uračunatim PDV-om i nema skrivenih troškova.', 'Sve cene su sa uračunatim PDV-om i nema skrivenih troškova.');
    pll_register_string('Plaćanje platnom karticom', 'Plaćanje platnom karticom');
    pll_register_string(
        'Terms error message',
        'Molimo Vas da pročitate i prihvatite uslove kako biste nastavili sa plasiranjem narudžbine.',
        'WooCommerce'
    );
    pll_register_string('Processing', 'Processing...',);
    pll_register_string('Adding to cart', 'Adding to cart',);
    pll_register_string('Fill all fields', 'Fill all fields',);
    pll_register_string('Došlo je do greške pri komunikaciji sa serverom. Pokušajte ponovo.', 'Došlo je do greške pri komunikaciji sa serverom. Pokušajte ponovo.');
    pll_register_string('Broj narudžbine', 'Broj narudžbine');
    pll_register_string('Datum', 'Datum');
    pll_register_string('Ukupno', 'Ukupno');
    pll_register_string('Način plaćanja', 'Način plaćanja');
    pll_register_string('Nastavite sa plaćanjem', 'Nastavite sa plaćanjem');
    pll_register_string('Vege paketi', 'Vege paketi');
    pll_register_string('Sledeća nedelja', 'Sledeća nedelja');
    pll_register_string('Ova nedelja', 'Ova nedelja');
	pll_register_string('Tip menija', 'Tip menija');
	pll_register_string('Standardni paketi', 'Standardni paketi');
});